name: 'Find Schema Changes'
description: 'Rough check for public schema references blah'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Find Schema Changes
      run: bash ./pg-public.sh
