name: gha action ci

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yaml
      - 'action-*/**' # By convention please name your actions action-<action-name>

jobs:
  update_tags:
    name: ci tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Determine Changed Actions
      id: changed_actions
      run: |
        git fetch
        git diff --name-only 'origin/main' '${{ github.sha }}' \
          | awk -F '/' '{print $1}' \
          | uniq > ./changed_actions.txt

        CHANGED_ACTIONS=$(cat ./changed_actions.txt) && \
        echo "changed_actions=${CHANGED_ACTIONS}" >> $GITHUB_ENV

    - name: Verify Version Update and README.md Presence
      if: env.changed_actions != ''
      run: |
        ERRORS=''
        for action in ${{ env.changed_actions }}; do
          if [ ! -f "$action/README.md" ]; then
            ERRORS="${ERRORS}\nERROR: $action/VERSION not found."
          elif git diff --quiet "$action/VERSION"; then
            ERRORS="${ERRORS}\nERROR: $action/VERSION has not been updated."
          fi
          if [ ! -f "$action/README.md" ]; then
            ERRORS="${ERRORS}\nERROR: $action/README.md not found."
          fi
          if [ ! -f "$action/action.yaml" ]; then
            ERRORS="${ERRORS}\nERROR: $action/action.yaml does not exist."
          fi
        done
        if [ -n "$ERRORS" ]; then
          printf $ERRORS
          exit 1
        fi

    - name: Update Tags
      if: env.changed_actions != ''
      run: |
        for action in ${{ env.changed_actions }}; do
          cd "$action"
          version=$(<VERSION)
          git tag -a "v$version" -m "Release $version"
          git push origin "v$version"
          cd ..
        done
